### PR TITLE
Added webhookBody to the query params

### PR DESCRIPTION
**Pull request by karlclement**
Now you can specify the response format posted to the endpoint for your web hook. Needed!!!

### CODE REVIEW

**Comment by karlclement** [comment]
@3rd-Eden This one ok? :+1:

**Comment by AdriVanHoudt** [comment]
Can you add a test?

**Comment by karlclement** [comment]
@AdriVanHoudt how about now?

**Comment by AdriVanHoudt** [comment]
LGTM, @3rd-Eden?

**Comment by karlclement** [comment]
@3rd-Eden @AdriVanHoudt :smile:

**Comment by 3rd-Eden** [comment]
Yeah, sorry. LGTM <3 thanks for the pull req and the patience ;D

**Pull request merged**
